const actions = {
  START_LOAD: 'START_LOAD',
  END_LOAD: 'END_LOAD',
  REMOVE_CUSTOMER_TURN: 'REMOVE_CUSTOMER_TURN',
  UNLOCK_BARISTA: 'UNLOCK_BARISTA',
  LOCK_BARISTA: 'LOCK_BARISTA',
  ADD_CUSTOMER_TURN: 'ADD_CUSTOMER_TURN',
};

export { actions };
